### ISSUE TITLE
服务端整合包无法正常运行 不知道是什么导致

### ISSUE THREAD

**Issue by china-us** [LaoZuan/Create-to-Sky#5]
[debug.log](https://github.com/LaoZuan/Create-to-Sky/files/9637705/debug.log)
[latest.log](https://github.com/LaoZuan/Create-to-Sky/files/9637707/latest.log)
这是最新的版本0.90版本

**Comment by KuroPeach** [comment]
删掉客户端辅助mod，光影铷之类

**Comment by china-us** [comment]
> 删掉客户端辅助mod，光影铷之类
我用的是作者提供的服务端哪里来的客户端辅助mod

**Comment by china-us** [comment]
> 删掉客户端辅助mod，光影铷之类

我用的是作者提供的服务端 哪里来的铷之类的mod

**Comment by china-us** [comment]
已解决
